name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Adjust as per your repository
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Ensure it's the latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Ensure it's the latest version

      - name: Login to DockerHub
        uses: docker/login-action@v3  # Ensure it's the latest version
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5  # Ensure it's the latest version
        with:
          context: ./backend  # Directory of the backend Dockerfile
          file: ./backend/Dockerfile  # Dockerfile path for the backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5  # Ensure it's the latest version
        with:
          context: ./frontend  # Directory of the frontend Dockerfile
          file: ./frontend/Dockerfile  # Dockerfile path for the frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
