name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to your default branch
  pull_request:
    branches:
      - master  # Run the workflow for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Add your DockerHub username to Secrets
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # Add your DockerHub access token to Secrets

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend  # Directory where the Dockerfile for backend is located
          file: ./backend/Dockerfile  # Dockerfile path for backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend  # Directory where the Dockerfile for frontend is located
          file: ./frontend/Dockerfile  # Dockerfile path for frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/deployment  # Replace with your actual path on the server
            docker-compose down
            docker-compose pull
            docker-compose up -d
